# Generated by Django 4.2.13 on 2026-06-28 21:27

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=applications.models.create_application_id, editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under review', 'Under review'), ('Interview needed', 'Interview needed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=32)),
                ('note', models.TextField(default='Your application is in the review queue. Check this site for updates before your interview is scheduled.')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=80)),
                ('showroom', models.CharField(max_length=180)),
                ('networth', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=120)),
                ('management_years', models.CharField(max_length=80)),
                ('management_history', models.TextField(blank=True)),
                ('online_interview', models.CharField(max_length=80)),
                ('id_proof', models.FileField(upload_to=applications.models.upload_to_application)),
                ('cv', models.FileField(blank=True, null=True, upload_to=applications.models.upload_to_application)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
