# Generated by Django 4.2.13 on 2026-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapplication',
            name='note',
            field=models.TextField(default='Your application is pending review. Check this site for updates from the admin team.'),
        ),
        migrations.AlterField(
            model_name='managerapplication',
            name='status',
            field=models.CharField(choices=[('Pending review', 'Pending review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending review', max_length=32),
        ),
    ]
