# Generated by Django 5.2.15 on 2026-06-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_managerapplication_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerapplication',
            name='car_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
